import { useState } from 'react';
import { ResponsiveImage } from './components/ResponsiveImage';
import { SocialLinks } from './components/SocialLinks';
import { BlurIntro } from './components/motion/BlurIntro';
import { CuriosityCode } from './components/motion/CuriosityCode';
import { ExploreLink } from './components/motion/ExploreLink';
export default function App() { const [menuOpen, setMenuOpen] = useState(false); return <><a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><a href="#home" className="wordmark" aria-label="Christian Osorno home">christian<span>®</span></a><span className="header-location mono">Cebu, PH <span aria-hidden="true">↗</span> Available for an internship</span><button className="menu-toggle" aria-expanded={menuOpen} aria-controls="main-nav" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? 'Close ×' : 'Menu +'}</button><nav id="main-nav" className={menuOpen ? 'is-open' : ''} aria-label="Main navigation" onKeyDown={e => { if (e.key === 'Escape') { setMenuOpen(false); document.querySelector<HTMLButtonElement>('.menu-toggle')?.focus(); } }}>{[['Work', '#work'], ['About', '#about'], ['Archive', '#archive'], ['Let’s talk ↗', '#contact']].map(([name, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{name}</a>)}</nav></header>
    <main id="main"><div id="home">
      <section className="hero" aria-labelledby="hero-title"><div className="hero-meta mono"><span>Christian A. Osorno / Portfolio</span><span>Built with curiosity. Made in Cebu.</span></div><div className="hero-title-wrap" data-motion="hero-title"><h1 id="hero-title"><span>DESIGNER’S EYE.</span><span>DEVELOPER’S MIND.</span></h1><span className="hero-spark" aria-hidden="true">✳</span></div><div className="hero-bottom"><div className="hero-intro"><BlurIntro className="serif" lines={['A little instinct.', 'A lot of intention.']} /><p>I’m Christian — a <strong>Software Engineer, UI/UX Designer & AI Automation Engineer</strong> turning complex ideas into things that feel simple.</p><div className="hero-actions"><ExploreLink /></div><div className="hero-socials"><span className="mono">ELSEWHERE /</span><SocialLinks compact includeResume /></div></div><div className="hero-collage" data-motion="hero-collage"><div className="collage-code mono" aria-hidden="true"><span>const perspective = {'{'}</span><span>  design: 'human',</span><span>  code: 'considered',</span><CuriosityCode /><span>{'}'};</span></div><figure className="portrait-card"><ResponsiveImage src="/Formal_Picture.png" alt="Christian A. Osorno" portrait eager /><figcaption className="mono">Christian A. Osorno / Cebu, PH</figcaption></figure><span className="collage-sticker">MADE TO<br /><em>make sense.</em></span><span className="collage-note serif">hello, world.</span></div><a className="internship-note" href="#contact"><span className="availability-dot" />Open for a<br /><strong>240-hour internship</strong><span aria-hidden="true">↗</span></a></div></section>
      </div>
      </main></>; }
